# Generated by Django 3.1.1 on 2020-09-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='color_choice',
        ),
    ]
